### ISSUE TITLE
ゴール条件の実装

### ISSUE THREAD

**Issue by Ogame3334** [Ogame3334/bnscup2023#13]

**Comment by Ogame3334** [comment]
ステージ右下にゴールとなる出口を置き、そこを通過するとクリアフラグを立てる
クリアフラグはシーンにおいておけばよい

**Comment by TOMOQ1024** [comment]
プレイヤーが右端のタイルの中心を跨いだときにクリアとなるよう設定した．
シーン側からは`Player::update`メソッドの戻り値としてクリア条件を満たしたかどうかを取得でき，それによってフラグを更新することでクリア状態を管理できる．
d7c2655f4031bee2a15c746ad3a34045d3828381
