### ISSUE TITLE
プレイヤークラスの実装

### ISSUE THREAD

**Issue by rarara1205** [Ogame3334/bnscup2023#3]

**Comment by TOMOQ1024** [comment]
やる

**Comment by TOMOQ1024** [comment]
クラスの追加 369258e4aaed1dc889b47c4107e8b92cbcc88c87

**Comment by TOMOQ1024** [comment]
物理演算 84f6beb560239d4c10672958af115ef36484ff27

**Comment by Ogame3334** [comment]
・操作とアニメーションの接続
・はしご上り下り
・タイルへのアクセス

**Comment by TOMOQ1024** [comment]
アニメーション 9f5d8899dced552b8f78f314d272ae2306c2f770
ハシゴアニメーション 7a520581231c122fb2137c9d68c494dd83cbd4dc
タイルへのアクセス 98ded590ee7bb1e6d951368318a462f38cdb7ba2

**Comment by TOMOQ1024** [comment]
~~- [ ] ハシゴの上部で跳ねないようにする~~

**Comment by Ogame3334** [comment]
水汲み https://github.com/Ogame3334/bnscup2023/commit/5f091b0da2c0703c5e4644c4a13c736030aac139
コンフリクト解消のバグ修正 https://github.com/Ogame3334/bnscup2023/commit/499d613834e2496d870f309b05d1c9e8cdc94562
